language: python
python:
  - "2.7"

env:
  # the 'relengapi' command wants a settings file, but the contents
  # aren't terribly important, so the example will do fine
  - RELENGAPI_SETTINGS=settings_example.py

# command to install dependencies
install: "pip install -e base[test] -e docs[test]"

# command to run tests
script:
  - relengapi run-tests
  - relengapi build-docs
