language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -e .[test]"
  - "pip freeze"

# run everything in a single script, so we get a nice summary at the end
script:
  - bash ./validate.sh
  # run the old client tests
  - bash test.sh
  - python test_tooltool.py
