language: python
python:
  - "2.7"

env:
  # the 'relengapi' command wants a settings file, but the contents
  # aren't terribly important, so the example will do fine.  This is
  # relative to the directory containing app.py, although Flask does not
  # document that.
  - RELENGAPI_SETTINGS=../../settings_example.py

# command to install dependencies
install: "pip install -e base[test] -e docs[test]"

# run everything in a single script, so we get a nice summary at the end
script:
  - sh base/validate.sh
