version: "2.1"

# TODO: what links do we need?
services:
  releng_db:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=releng
      - POSTGRES_USER=releng
      - POSTGRES_DB=releng
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data

  releng_frontend:
    image: mozbhearsum/bhearsum-shipit-test
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SERVICES_APP=releng_frontend

  releng_clobberer:
    image: mozbhearsum/bhearsum-shipit-test
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SERVICES_APP=releng_clobberer

  releng_tooltool:
    image: mozbhearsum/bhearsum-shipit-test
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SERVICES_APP=releng_tooltool

  releng_treestatus:
    image: mozbhearsum/bhearsum-shipit-test
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SERVICES_APP=releng_treestatus
      - DATABASE_URL=postgresql://releng:releng@releng_db:5432/releng
    links:
      - releng_db
    healthcheck:
      # TODO: this command generates spamming output from the releng_db container
      # using the real pg client might fix this
      test: ["CMD", "nc", "-vz", "releng_db", "5432"]
      interval: 15s
      timeout: 2s
      retries: 10

  releng_mapper:
    image: mozbhearsum/bhearsum-shipit-test
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SERVICES_APP=releng_mapper

  releng_archiver:
    image: mozbhearsum/bhearsum-shipit-test
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SERVICES_APP=releng_archiver
